pipeline {
  agent {
    docker { image 'node:17-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
        stage('Deploy') {
      steps {
        sh 'kubectl apply -f deployment.yml'
      }
    }
        stage('Test1') {
      steps {
        sh 'node --version'
      }
    }
  }
}
